gqlgen-server:
  port: 3000
products-server:
  port: 50051
database:
  username: token
  token: token
  path : ./secure-connect.zip
queue:
  uri: pulsar+ssl://pulsar-aws-eucentral1.streaming.datastax.com:6651
  topic: persistent://witty-cluster/default/products-topic
  token: pulsar_token
  