// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Category struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
}

type CreateCategoryInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type CreateOrderInput struct {
	UserID string            `json:"userId"`
	Items  []*OrderItemInput `json:"items"`
}

type CreateProductInput struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Stock       int32   `json:"stock"`
	CategoryID  string  `json:"categoryId"`
}

type ListOrdersResponse struct {
	Orders      []*Order `json:"orders"`
	PagingState *string  `json:"pagingState,omitempty"`
}

type ListProductsResponse struct {
	Products    []*Product `json:"products"`
	PagingState *string    `json:"pagingState,omitempty"`
}

type Mutation struct {
}

type OrderItem struct {
	ProductID string  `json:"productId"`
	Quantity  int32   `json:"quantity"`
	UnitPrice float64 `json:"unitPrice"`
}

type OrderItemInput struct {
	ProductID string  `json:"productId"`
	Quantity  int32   `json:"quantity"`
	UnitPrice float64 `json:"unitPrice"`
}

type Query struct {
}
